version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    networks:
      - app-network
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge
